/**
 * Auto-generated sidebar configuration from Hugo content
 * Generated by: scripts/migrate-hugo.js
 */

export default {
  "tutorialSidebar": [
    {
      "type": "category",
      "label": "Posts",
      "items": [
        {
          "type": "category",
          "label": "Junos",
          "items": [
            {
              "type": "doc",
              "id": "junos/tagging",
              "label": "Tagging"
            }
          ]
        }
      ]
    }
  ]
};
